#!/usr/bin/env python3
"""Render a clear, standalone dashboard from a BlazePDF benchmark JSON file."""
import argparse, html, json
from pathlib import Path
from render_workload_graphs import sample_count_label

ROOT=Path(__file__).resolve().parents[1]

def main():
 p=argparse.ArgumentParser();p.add_argument('input',type=Path);p.add_argument('output',type=Path);a=p.parse_args()
 d=json.loads(a.input.read_text(encoding='utf-8')); d['sample_count_label']=sample_count_label(d); payload=json.dumps(d,separators=(',',':')).replace('<','\\u003c')
 h='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BlazePDF · benchmark dashboard</title><style>
:root{--ink:#10233d;--muted:#64748b;--paper:#f4f7fb;--line:#dce4ef;--blue:#2563d9;--green:#058873;--amber:#b7791f}*{box-sizing:border-box}body{margin:0;background:var(--paper);font:14px system-ui;color:var(--ink)}header{background:linear-gradient(125deg,#0b1e35,#1d4f91);color:#fff;padding:48px max(22px,calc((100% - 1180px)/2))}h1{font-size:40px;letter-spacing:-1.4px;margin:0}.sub,.muted{color:var(--muted)}header .sub{color:#c8d8ee}main{max-width:1180px;margin:auto;padding:25px 22px 60px}h2{font-size:18px;margin:30px 0 12px}.notice{background:#e8f0ff;border-left:4px solid var(--blue);padding:14px 16px;border-radius:6px;color:#304e72}.board,.chart,.tablewrap,.filters{background:#fff;border:1px solid var(--line);border-radius:12px}.board{padding:16px}.race{display:grid;grid-template-columns:190px 1fr 180px;gap:14px;align-items:center;padding:11px 0;border-bottom:1px solid #edf0f5}.race:last-child{border:0}.label b,.winner{display:block}.label small{color:var(--muted)}.bars{display:grid;gap:5px}.barrow{display:grid;grid-template-columns:130px 1fr 76px;gap:8px;align-items:center;font-size:12px}.track{height:10px;background:#e8edf5;border-radius:20px;overflow:hidden}.fill{height:100%;background:#9ab8ef;border-radius:20px}.best .fill{background:linear-gradient(90deg,var(--green),var(--blue))}.best .name{font-weight:700;color:var(--green)}.gap{text-align:right;font-weight:700}.filters{padding:14px;display:flex;gap:14px;flex-wrap:wrap;margin:16px 0}label{display:grid;gap:5px;font-size:12px;font-weight:700;color:#53667e}select{padding:8px;border:1px solid var(--line);border-radius:7px;background:#fff}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.metric{background:#fff;border:1px solid var(--line);border-radius:10px;padding:14px}.metric b{font-size:25px;display:block;margin-top:4px}.chart{padding:16px;margin-top:16px}svg{width:100%;height:310px}.grid{stroke:#e4eaf2}.axis{fill:#64748b;font-size:11px}.tablewrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th{background:#f1f5fa;text-align:left;color:#53667e;font-size:11px;text-transform:uppercase;position:sticky;top:0}td,th{padding:10px 12px;border-bottom:1px solid #e9edf3;white-space:nowrap}.num{text-align:right;font-variant-numeric:tabular-nums}.ok{color:var(--green);font-weight:700}.failed{color:#bd4050;font-weight:700}.skipped{color:var(--amber);font-weight:700}@media(max-width:720px){header{padding:32px 20px}h1{font-size:31px}main{padding:18px 12px}.race{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.barrow{grid-template-columns:110px 1fr 68px}}
</style><header><div style="letter-spacing:1.3px;font-size:11px;font-weight:700;color:#9dc7ff">PERFORMANCE LAB · REPRODUCIBLE RUN</div><h1>BlazePDF benchmark</h1><p class="sub" id="meta"></p></header><main><div class="notice">Each race compares only readers performing the identical workload. One warm-up is excluded; lower latency wins. Failed and unavailable readers stay visible in the evidence table below.</div><h2>Who wins each benchmark?</h2><div class="board" id="board"></div><div class="filters"><label>Workload<select id="work"><option value="all">All workloads</option></select></label><label>Reader<select id="reader"><option value="all">All readers</option></select></label></div><div class="metrics" id="metrics"></div><section class="chart"><h2 id="charttitle">Median latency by reader</h2><svg id="chart" role="img" aria-label="Latency comparison"></svg></section><h2>Full evidence table</h2><div class="tablewrap"><table><thead><tr><th>Reader</th><th>Workload</th><th>Document</th><th>Size</th><th>Status</th><th class="num">Min</th><th class="num">Mean</th><th class="num">Median</th><th class="num">p95</th><th class="num">Max</th><th class="num">Stdev</th><th class="num">CV</th></tr></thead><tbody id="rows"></tbody></table></div></main><script>
const D=__DATA__,R=D.measurements,$=x=>document.getElementById(x),fm=n=>n==null?'—':n>=1000?(n/1000).toFixed(2)+' s':n.toFixed(1)+' ms',fb=n=>n<1e6?(n/1e3).toFixed(0)+' KB':(n/1e6).toFixed(2)+' MB';$('meta').textContent=D.generated_at+' · '+D.machine.platform+' · '+D.repeats+' measured runs per case'+(D.merged_from?' · merged from '+D.merged_from.length+' runs: '+D.merged_from.map(s=>s.file+' ('+s.measurements_used+')').join(', '):'');[...new Set(R.map(x=>x.work))].forEach(x=>$('work').innerHTML+=`<option>${x}</option>`);[...new Set(R.map(x=>x.reader))].forEach(x=>$('reader').innerHTML+=`<option>${x}</option>`);
function visible(){let w=$('work').value,r=$('reader').value;return R.filter(x=>x.status==='ok'&&(w==='all'||x.work===w)&&(r==='all'||x.reader===r))}function board(){let g={};R.filter(x=>x.status==='ok').forEach(x=>(g[x.work+'|'+x.document]??=[]).push(x));$('board').innerHTML=Object.entries(g).map(([k,v])=>{v.sort((a,b)=>a.median_ms-b.median_ms);let best=v[0],slow=v[v.length-1],gain=v.length>1?((slow.median_ms/best.median_ms-1)*100).toFixed(0)+'% faster':'only runnable reader';return `<div class="race"><div class="label"><b>${best.document}</b><small>${best.work}</small></div><div class="bars">${v.map((x,i)=>`<div class="barrow ${i===0?'best':''}"><span class="name">${x.reader}</span><span class="track"><i class="fill" style="width:${Math.max(8,100*best.median_ms/x.median_ms)}%"></i></span><span>${fm(x.median_ms)}</span></div>`).join('')}</div><div class="gap">${best.reader}<br><span class="muted">${gain}</span></div></div>`}).join('')||'<span class="muted">No comparable results yet.</span>'}
function draw(){let v=visible(),a={};v.forEach(x=>(a[x.reader]??=[]).push(x.median_ms));let z=Object.entries(a).map(([n,x])=>[n,x.reduce((q,w)=>q+w)/x.length]).sort((x,y)=>x[1]-y[1]),s=$('chart'),w=s.clientWidth,h=310,L=175,max=Math.max(1,...z.map(x=>x[1]));s.setAttribute('viewBox',`0 0 ${w} ${h}`);let out='';for(let i=0;i<5;i++){let x=L+(w-L-25)*i/4;out+=`<line class="grid" x1="${x}" y1="22" x2="${x}" y2="275"/><text class="axis" x="${x}" y="298" text-anchor="middle">${fm(max*i/4)}</text>`}z.forEach(([n,x],i)=>{let y=28+i*240/Math.max(z.length,1),bh=Math.max(15,240/Math.max(z.length,1)-10);out+=`<text class="axis" x="${L-9}" y="${y+bh/2+4}" text-anchor="end">${n}</text><rect x="${L}" y="${y}" width="${(w-L-25)*x/max}" height="${bh}" rx="4" fill="${i===0?'#058873':'#2563d9'}"><title>${n}: ${fm(x)}</title></rect>`});s.innerHTML=out;$('charttitle').textContent='Mean document median — '+($('work').value==='all'?'selected workloads':$('work').value)}function table(){let w=$('work').value,r=$('reader').value;$('rows').innerHTML=R.filter(x=>(w==='all'||x.work===w)&&(r==='all'||x.reader===r)).map(x=>`<tr><td>${x.reader}</td><td>${x.work}</td><td>${x.document}</td><td>${fb(x.bytes)}</td><td class="${x.status}">${x.status}</td><td class="num">${fm(x.min_ms)}</td><td class="num">${fm(x.mean_ms)}</td><td class="num">${fm(x.median_ms)}</td><td class="num">${fm(x.p95_ms)}</td><td class="num">${fm(x.max_ms)}</td><td class="num">${fm(x.stdev_ms)}</td><td class="num">${x.cv_percent==null?'—':x.cv_percent+'%'}</td></tr>`).join('')}function render(){let v=visible(),runs=v.reduce((n,x)=>n+x.samples_ms.length,0),mean=v.length?v.reduce((n,x)=>n+x.median_ms,0)/v.length:0;$('metrics').innerHTML=`<div class="metric"><span class="muted">Successful cases</span><b>${v.length}</b></div><div class="metric"><span class="muted">Measured runs</span><b>${runs}</b></div><div class="metric"><span class="muted">Mean case median</span><b>${fm(mean)}</b></div><div class="metric"><span class="muted">Input range</span><b>${v.length?fb(Math.min(...v.map(x=>x.bytes)))+'–'+fb(Math.max(...v.map(x=>x.bytes))):'—'}</b></div>`;draw();table()}$('work').onchange=render;$('reader').onchange=render;new ResizeObserver(render).observe($('chart'));board();render();
</script>'''.replace('__DATA__',payload)
 h=h.replace("D.repeats+' measured runs per case'", "D.sample_count_label")
 machine_css = '.machine{background:#fff;border:1px solid var(--line);border-radius:12px;padding:16px;margin:16px 0}.machine h2{margin:0 0 12px}.machine-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.machine-grid div{background:#f5f7fb;border-radius:8px;padding:10px}.machine-grid b,.machine-grid span{display:block}.machine-grid b{font-size:11px;color:var(--muted);text-transform:uppercase}.machine-grid span{margin-top:3px;word-break:break-word}@media(max-width:720px){.machine-grid{grid-template-columns:repeat(2,1fr)}}'
 machine_js = "const M=D.machine||{},machineFields=[['os','OS'],['cpu_model','CPU'],['cpu_count','Logical CPUs'],['memory_gb','RAM (GB)'],['gpu','GPU'],['python','Python'],['build_profile','Build']];$('machine').innerHTML=machineFields.map(([key,label])=>`<div><b>${label}</b><span>${M[key]??'unknown'}</span></div>`).join('');"
 h=h.replace('</style>',machine_css+'</style>')
 h=h.replace('</div><h2>Who wins each benchmark?</h2>','</div><section class="machine"><h2>Test machine</h2><div class="machine-grid" id="machine"></div></section><h2>Who wins each benchmark?</h2>',1)
 h=h.replace("$('meta').textContent", machine_js+"$('meta').textContent", 1)
 catalog=''.join('<tr><td><a href="'+html.escape(x['source'],quote=True)+'">'+html.escape(x['name'])+'</a></td>'+''.join(f'<td>{html.escape(str(value))}</td>' for value in (x['kind'],x['platforms'],x['features'],x['claim'], '; '.join(x['tests']) or 'unresolved; not scored'))+'</tr>' for x in d.get('catalog',[]))
 panel='<h2>Product field & performance notes</h2><p class="muted">Catalog membership is not a score. Feature descriptions and performance claims come from the linked vendor/project source; claims remain unverified until measured.</p><div class="table"><table><thead><tr><th>Product</th><th>Type</th><th>Platforms</th><th>Features</th><th>Claim / caveat</th><th>Candidate tests</th></tr></thead><tbody>'+catalog+'</tbody></table></div>'
 h=h.replace('<footer>',panel+'<footer>')
 a.output.write_text(h,encoding='utf-8')
if __name__=='__main__':main()
